default:
  google_device_id: None  # if None, tries to use MAC Address of PC
  spotipy_client_id: <your-spotify-client-id>  # overwrite in settings.local.yaml
  spotipy_client_secret: <your-spotify-client-secret>  # overwrite in settings.local.yaml
  spotipy_client_username: <your-spotify-client-username>
  spotipy_redirect_uri: http://localhost:8080
  spotipy_scope: playlist-modify-public
  token_path: .tokens
